name: MERN Fullstack CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout source code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Setup Node for backend
      - name: Setup Node for backend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      # Run backend tests (optional)
      # - name: Run backend tests
      #   working-directory: ./backend
      #   run: npm test
      
      # Setup Node for frontend
      - name: Setup Node for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install
        
      # Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        
      # Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to DockerHub (optional, set secrets)
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images (optional push)
      - name: Build Docker images
        run: docker compose build

      # Run Docker Compose to deploy containers
      - name: Deploy Docker Containers
        run: docker compose up -d
